---
# file: auth.yml

- name: auth | disallow root SSH access
  sudo: yes
  lineinfile: >
    dest=/etc/ssh/sshd_config
    regexp="^PermitRootLogin"
    line="PermitRootLogin no"
    state=present
  notify: restart sshd
